{% set name = "graphene" %}
{% set version = "1.10.2" %}
{% set sha256 = "e97de8208f1aac4f913d4fa71ab73a7034e807186feb2abe55876e51c425a7f6" %}

package:
    # graphene is already taken by an unrelated python package
    name: "lib{{ name|lower }}"
    version: {{ version }}

source:
    sha256: {{ sha256 }}
    url: http://ftp.gnome.org/pub/gnome/sources/{{ name }}/{{ '.'.join(version.split('.')[:2]) }}/{{ name }}-{{ version }}.tar.xz

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - meson
    - ninja
    - gobject-introspection
  host:
    - glib
  run:
    - libglib

test:
  requires:
    - pkg-config

  commands:
    # verify that libs get installed and can be located through pkg-config
    {% set pc = "graphene-1.0" %}
    {% set lib = "graphene-1.0" %}
    {% set gi = "Graphene-1.0" %}
    - "test -f $PREFIX/lib/lib{{ lib }}${SHLIB_EXT}"  # [unix]
    - "test -f `pkg-config --variable=libdir --dont-define-prefix {{ pc }}`/lib{{ lib }}${SHLIB_EXT}"  # [unix]
    - "if not exist %PREFIX%\\Library\\bin\\{{ lib }}-0.dll exit 1"  # [win]
    - "for /f "usebackq tokens=*" %%a in (`pkg-config --variable=exec_prefix --dont-define-prefix {{ pc }}`) do if not exist "%%a/bin/{{ lib }}-0.dll" exit 1"  # [win]
    - "if not exist %PREFIX%\\Library\\lib\\{{ lib }}.lib exit 1"  # [win]
    - "for /f "usebackq tokens=*" %%a in (`pkg-config --variable=libdir --dont-define-prefix {{ pc }}`) do if not exist "%%a/{{ lib }}.lib" exit 1"  # [win]
    - "test -f $PREFIX/lib/girepository-1.0/{{ gi }}.typelib"  # [unix]
    - "if not exist %PREFIX%\\Library\\lib\\girepository-1.0\\{{ gi }}.typelib exit 1"   # [win]


about:
  home: https://developer.gnome.org/gdk-pixbuf/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Thin layer of graphic data types"

extra:
  recipe-maintainers:
    - tschoonj
